name: Trigger auto deployment for container-app-dnaxxhdhbo3to

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - 'server/**'
    - '.github/workflows/container-app-dnaxxhdhbo3to-AutoDeployTrigger-f448d02e-c9f0-4b2d-bec8-e3779b1ad297.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPDNAXXHDHBO3TO_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPDNAXXHDHBO3TO_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPDNAXXHDHBO3TO_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/server 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPDNAXXHDHBO3TO_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPDNAXXHDHBO3TO_REGISTRY_PASSWORD }}
          containerAppName: container-app-dnaxxhdhbo3to
          resourceGroup: appspacesragapp9b35b40e
          imageToBuild: default/container-app-dnaxxhdhbo3to:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


